[theme]
primaryColor = "#E65100"          # Naranja de seguridad para botones
backgroundColor = "#1E1E1E"       # Fondo oscuro
secondaryBackgroundColor = "#2D2D2D" # Fondo de tarjetas y menús
textColor = "#FFFFFF"             # Texto blanco
font = "sans serif"